### ISSUE TITLE
Several API bugs in conditional tokens

### ISSUE THREAD

**Issue by vporton** [gnosis/conditional-tokens-contracts#113]
See https://github.com/gnosis/conditional-tokens-contracts/pull/111#issuecomment-747189086

**Comment by cag** [comment]
> Oh, so this isn't a straight port? I think in the future, it would be nice to get that in two PRs, but since you're here, mind elaborating on what was fixed?
> 
> I don't remember all the details, but some function had return values that were never assigned.

I'm not sure what is meant by assigned, but values that are not stored can be derived from input parameters, and don't need to be stored. If a specific issue is raised and a line of code can be pointed to that is an actual issue, then reopen this. Otherwise, please refrain from opening issues with not enough details.

**Comment by vporton** [comment]
Ugh, the bug was in my (human) memory, not in the code.
